Update autograding workflow

diff --git a/.github/workflows/classroom.yml b/.github/workflows/classroom.yml
--- a/.github/workflows/classroom.yml
+++ b/.github/workflows/classroom.yml
@@ -17,13 +17,14 @@ jobs:
         uses: actions/checkout@v2
 
       - name: Check if specific files exist
-      run: |
-        # Search repo for necessary files
-        if [ -f "index.html" ] && [ -f "styles.css" ] && [ -f "login.html" ] && [ -f "register.css" ] && [ -f "add_expense.html" ] && [ -f "edit_expense.html" ] && [ -f "view_expense.html" ]; then
-          echo "Files exist."
-        else
-          echo "Error: Files not found."
-          exit 1
+        run: |
+         # Search repo for necessary files
+         if [ -f "index.html" ] && [ -f "styles.css" ] && [ -f "login.html" ] && [ -f "register.css" ] && [ -f "add_expense.html" ] && [ -f "edit_expense.html" ] && [ -f "view_expense.html" ]; then
+           echo "Files exist."
+         else
+           echo "Error: Files not found."
+           exit 1
+         fi
 
       - name: Check HTML structure
         run: |
