Update autograding workflow

diff --git a/.github/workflows/classroom.yml b/.github/workflows/classroom.yml
--- a/.github/workflows/classroom.yml
+++ b/.github/workflows/classroom.yml
@@ -28,12 +28,12 @@ jobs:
 
       - name: Check HTML structure
         run: |
-          # Search for the existence of required HTML tags
-          if grep -q "<!DOCTYPE>" $(git ls-files '*.html'); then
-            echo "HTML tag <DOCTYPE> found in the repository."
+          # Search repo for necessary files
+          if [ -f "index.html" ] && [ -f "styles.css" ] && [ -f "login.html" ] && [ -f "register.css" ] && [ -f "add_expense.html" ] && [ -f "edit_expense.html" ] && [ -f "view_expense.html" ]; then
+            echo "Files exist."
           else
-           echo "Error: HTML tag <tag_name> not found in any HTML file."
-          exit 1
+            echo "Error: Files not found."
+            exit 1
           fi
           
           if grep -q "<html>" $(git ls-files '*.html'); then
